# This is a basic workflow to help you get started with Actions

name: Update database

# Controls when the workflow will run
on:
  schedule:
    - cron: "30 * * * *"   # Every hour
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Install yt-dlp
        run: pip install -U yt-dlp
  
      - name: Download list of videos
        run: yt-dlp --flat-playlist --print id https://www.youtube.com/@ateuinforma > index.db

      - name: Push files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update subtitles $(date)"
          git push
