# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Convert subtitle to markdown

# Controls when the workflow will run
on:
  # Triggered by another workflow
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade jsonpath-ng
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script for all subtitle files
      shell: bash
      run: python src/sub2md.py database/ content/posts/
    - name: Push files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git pull --rebase origin main
        git add .
        git commit -m "Update content $(date)"
        git push
  
