# This is a basic workflow to help you get started with Actions

name: Download subtitles

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 * * * *"   # Every hour

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install yt-dlp
        run: pip install -U yt-dlp
        
      - name: Create subs folder
        run: mkdir -p subs
        
      - name: Download subtitles
        run: |
          yt-dlp --write-auto-sub --sub-lang pt-orig --sub-format json3 \
            -o "subs/%(upload_date>%Y-%m-%d)s - %(title)s - %(id)s.%(ext)s" \
            --skip-download --restrict-filenames -w \
            --lazy-playlist --rate-limit 500k \
            https://www.youtube.com/@ateuinforma
      
      - name: Push files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update subtitles ${date}"
          git push
