# This is a basic workflow to help you get started with Actions

name: Download subtitles

# Controls when the workflow will run
on:
  # Triggered by another workflow
  workflow_call:
    inputs:
      video_id:
        required: true
        type: string

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      video_id:
        required: true
        type: string

permissions:
  contents: write
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    outputs:
      filename: ${{ steps.download.outputs.filename}}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: tor-actions/setup-tor@main
        with:
          daemon: true
          
      - name: Install yt-dlp
        run: pip install -U yt-dlp

      - name: Check IP address
        run: curl -x socks5://127.0.0.1:9050 -sL ip6.me/api | cut -f 2 -d,

      - name: List subtitles
        run: |
          yt-dlp --list-subs --skip-download \
            --proxy socks5://127.0.0.1:9050/ \
            "https://www.youtube.com/watch?v=${{ inputs.video_id }}"

      - name: Download subtitles
        id: download
        run: |
          yt-dlp --write-auto-sub --sub-lang pt-orig --sub-format json3 \
            -o "subs/%(upload_date>%Y-%m-%d)s/%(title)s/%(id)s.%(ext)s" \
            --skip-download --restrict-filenames -w \
            --lazy-playlist --rate-limit 500k \
            --proxy socks5://127.0.0.1:9050/ \
            "https://www.youtube.com/watch?v=${{ inputs.video_id }}"

      - name: Push files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update subtitles ${date}"
          git push
